# Generated by Django 3.0.7 on 2020-06-23 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='labels',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='user_tmp',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='project',
            name='labeled_photos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='photos_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
