# Generated by Django 3.0.7 on 2020-06-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200623_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user_tmp',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
