# Generated by Django 3.0.7 on 2020-07-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200624_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='labels',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
