# Generated by Django 3.0.8 on 2020-07-10 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_auto_20200629_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='labeled_photos',
        ),
        migrations.RemoveField(
            model_name='project',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='project',
            name='photos_total',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user_tmp',
        ),
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.AddField(
            model_name='project',
            name='owners',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
