# Generated by Django 3.0.8 on 2020-07-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('label_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.Label')),
                ('val', models.CharField(max_length=160)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='projects.Label')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='projects.Photo')),
            ],
            bases=('projects.label',),
        ),
    ]
