# Generated by Django 3.0.8 on 2020-07-10 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20200710_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='projects.Project'),
        ),
    ]
