# Generated by Django 3.0.8 on 2020-07-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20200711_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='labeled_photos',
            field=models.IntegerField(default=0),
        ),
    ]
