# Generated by Django 3.0.8 on 2020-07-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_project_labeled_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='labeled_photos',
        ),
    ]
