# Generated by Django 3.0.8 on 2020-07-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20200711_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.CharField(default='', max_length=512),
        ),
    ]
