# Generated by Django 3.0.8 on 2020-07-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20200711_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Value',
        ),
    ]
