# Generated by Django 3.0.8 on 2020-07-17 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_value_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='type',
        ),
        migrations.AddField(
            model_name='value',
            name='label',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='projects.Label'),
        ),
    ]
