# Generated by Django 3.0.8 on 2020-07-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20200718_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='values', to='projects.Label'),
        ),
    ]
