# Generated by Django 3.0.8 on 2020-07-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_remove_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
