# Generated by Django 3.0.8 on 2020-07-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_project_ownername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
