# Generated by Django 3.0.8 on 2020-07-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_auto_20200724_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='uploader',
            field=models.CharField(default='someone', max_length=160),
            preserve_default=False,
        ),
    ]
