steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/label-it-2020/lit/$BRANCH_NAME', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'python3', 'manage.py', 'makemigrations']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/label-it-2020/lit/$BRANCH_NAME']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'lit-$BRANCH_NAME'
  - '--image'
  - 'eu.gcr.io/label-it-2020/lit/$BRANCH_NAME'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
images:
- eu.gcr.io/label-it-2020/lit/$BRANCH_NAME
