steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/label-it-2020/lit/dev', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/label-it-2020/lit/dev']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'lit'
  - '--image'
  - 'eu.gcr.io/label-it-2020/lit/dev'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
images:
- eu.gcr.io/label-it-2020/lit/dev
