# Generated by Django 3.0.7 on 2020-06-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-last_name']},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(help_text='Please enter your email address.', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Please enter your firstname.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Please enter your lastname.', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='pwd',
            field=models.EmailField(help_text='Please enter your password.', max_length=256),
        ),
    ]
