# Generated by Django 3.0.7 on 2020-06-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_auto_20200605_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(primary_key=True, help_text='Please enter your username.', max_length=20, serialize=False)),
                ('first_name', models.CharField(help_text='Please enter your firstname.', max_length=20)),
                ('last_name', models.CharField(help_text='Please enter your lastname.', max_length=30)),
                ('email', models.CharField(help_text='Please enter your email address.', max_length=25)),
                ('pwd', models.EmailField(help_text='Please enter your password.', max_length=256)),
            ],
            options={
                'ordering': ['-username'],
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
