# Generated by Django 3.0.7 on 2020-06-06 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_auto_20200605_1759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
